server:
  port: 9090
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 5000
    jedis:
      pool:
        # 连接池中的最大空闲连接，默认值也是8。
        max-idle: 500
        # 连接池中的最小空闲连接，默认值也是0。
        min-idle: 50
        # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
        max-active: 1000
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        max-wait: 2000


  #数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/examination_system?useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: yuanjiafei
    password: 123456

    #指定了使用 Hikari 连接池作为数据源，idle-timeout: 600000：设置了连接在池中空闲的最大时间，这里是 10 分钟，单位是毫秒，800000：指定了连接的最大存活时间，即连接在池中的最大生命周期，这里是 30
    #分钟，单位是毫秒。
    hikari:
      idle-timeout: 600000
      max-lifetime: 1800000

#  #热部署
#  devtools:
#    restart:
#      enabled: true
#      additional-paths: src/main/java


files:
  upload:
    filePath: ${user.dir}/src/main/resources/static/files/
    faceFilePath: ${user.dir}/src/main/resources/static/files/faces/
    avatarFilePath: ${user.dir}/src/main/resources/static/files/avatars/
    staticFilePath: ${user.dir}/src/main/resources/static
    tmpFaceFilePath: ${user.dir}/src/main/resources/static/files/faces/tmpFaceFilePath/

config:
  multifile:
    maxFileSize: 200000000  #最大支持文件大小
    maxRequestSize: 200000000  #最大支持请求大小

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



